@echo off
REM Quick deployment helper script for Windows
REM Run this after deploying your backend server to Render/Railway

echo.
echo 🚀 Asterocks Deployment Helper
echo ================================
echo.

REM Get backend URL from user
echo Step 1: What is your backend server URL?
echo Example: asterocks-server.onrender.com
echo          asterocks-server.up.railway.app
echo.
set /p BACKEND_URL="Backend URL (without https://): "

if "%BACKEND_URL%"=="" (
    echo ❌ No URL provided. Exiting.
    exit /b 1
)

echo.
echo Step 2: Updating config.js...

REM Update config.js
(
echo // Asterocks Configuration
echo // Auto-generated by deployment helper
echo.
echo window.ASTEROCKS_CONFIG = {
echo   // Backend WebSocket Server
echo   BACKEND_SERVER: '%BACKEND_URL%',
echo.  
echo   // Debug mode - set to true to see connection details in console
echo   DEBUG: false
echo };
) > public\config.js

echo ✅ Configuration updated!
echo.
echo Step 3: Review changes
echo File: public\config.js
echo Backend URL: %BACKEND_URL%
echo.
echo Step 4: Commit and push to deploy
echo Run:
echo   git add public\config.js
echo   git commit -m "Configure backend server"
echo   git push origin main
echo.
echo 🎮 After pushing, your game will auto-deploy to GitHub Pages!
echo Visit: https://YOUR-USERNAME.github.io/asterocks
echo.
pause
