#!/bin/bash
# Quick deployment helper script
# Run this after deploying your backend server to Render/Railway

echo "🚀 Asterocks Deployment Helper"
echo "================================"
echo ""

# Get backend URL from user
echo "Step 1: What is your backend server URL?"
echo "Example: asterocks-server.onrender.com"
echo "         asterocks-server.up.railway.app"
echo ""
read -p "Backend URL (without https://): " BACKEND_URL

if [ -z "$BACKEND_URL" ]; then
    echo "❌ No URL provided. Exiting."
    exit 1
fi

echo ""
echo "Step 2: Updating config.js..."

# Update config.js
cat > public/config.js << EOF
// Asterocks Configuration
// Auto-generated by deployment helper

window.ASTEROCKS_CONFIG = {
  // Backend WebSocket Server
  BACKEND_SERVER: '$BACKEND_URL',
  
  // Debug mode - set to true to see connection details in console
  DEBUG: false
};
EOF

echo "✅ Configuration updated!"
echo ""
echo "Step 3: Review changes"
echo "File: public/config.js"
echo "Backend URL: $BACKEND_URL"
echo ""
echo "Step 4: Commit and push to deploy"
echo "Run:"
echo "  git add public/config.js"
echo "  git commit -m \"Configure backend server\""
echo "  git push origin main"
echo ""
echo "🎮 After pushing, your game will auto-deploy to GitHub Pages!"
echo "Visit: https://YOUR-USERNAME.github.io/asterocks"
echo ""
